### ISSUE TITLE
CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.

### ISSUE THREAD

**Issue by hu6360567** [OldGrumpyViking/hatch-conda#7]
I'm using hatch-conda to create envirnoment and run script as expect, but fail to enter shell.

Config is list as below
```toml
[tool.hatch.envs.default]
dependencies = [
  "coverage[toml]>=6.5",
  "pytest",
]
type="conda"
python="3.8"
```

Error is list as below
```shell
CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.
```

My OS is MacOS 12.6.4, Shell is Zsh with oh-my-zsh, conda is miniconda3
